"""
Repository Ports

Defined in the domain layer — implementations live in infrastructure.
Per skill2026.md Rule 2: Interface-First Development.
"""

from __future__ import annotations

from typing import Protocol

from sentinel.domain.entities.agent import Agent
from sentinel.domain.entities.incident import Incident
from sentinel.domain.entities.mcp_server import MCPServer
from sentinel.domain.entities.threat import Threat
from sentinel.domain.entities.tool_call import ToolCall


class AgentRepositoryPort(Protocol):
    async def save(self, agent: Agent) -> None: ...
    async def get_by_id(self, agent_id: str) -> Agent | None: ...
    async def get_all(self) -> list[Agent]: ...
    async def delete(self, agent_id: str) -> None: ...


class ThreatRepositoryPort(Protocol):
    async def save(self, threat: Threat) -> None: ...
    async def get_by_id(self, threat_id: str) -> Threat | None: ...
    async def get_by_agent_id(self, agent_id: str) -> list[Threat]: ...
    async def get_open_threats(self) -> list[Threat]: ...


class IncidentRepositoryPort(Protocol):
    async def save(self, incident: Incident) -> None: ...
    async def get_by_id(self, incident_id: str) -> Incident | None: ...
    async def get_active_incidents(self) -> list[Incident]: ...


class MCPServerRepositoryPort(Protocol):
    async def save(self, server: MCPServer) -> None: ...
    async def get_by_id(self, server_id: str) -> MCPServer | None: ...
    async def get_all(self) -> list[MCPServer]: ...


class ToolCallRepositoryPort(Protocol):
    async def save(self, tool_call: ToolCall) -> None: ...
    async def get_by_agent_id(self, agent_id: str, limit: int = 100) -> list[ToolCall]: ...
    async def get_recent(self, limit: int = 100) -> list[ToolCall]: ...
